name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: mathclock_nine.tex 
      - run: mkdir -p pdf/
      - run: mv mathclock_nine.pdf  pdf/mathclock_nine.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: latex-artifact
          path: pdf/mathclock_nine.pdf

